// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getHappycatFactStmt, err = db.PrepareContext(ctx, getHappycatFact); err != nil {
		return nil, fmt.Errorf("error preparing query GetHappycatFact: %w", err)
	}
	if q.listHappycatFactsStmt, err = db.PrepareContext(ctx, listHappycatFacts); err != nil {
		return nil, fmt.Errorf("error preparing query ListHappycatFacts: %w", err)
	}
	if q.saveHappycatFactStmt, err = db.PrepareContext(ctx, saveHappycatFact); err != nil {
		return nil, fmt.Errorf("error preparing query SaveHappycatFact: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getHappycatFactStmt != nil {
		if cerr := q.getHappycatFactStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHappycatFactStmt: %w", cerr)
		}
	}
	if q.listHappycatFactsStmt != nil {
		if cerr := q.listHappycatFactsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listHappycatFactsStmt: %w", cerr)
		}
	}
	if q.saveHappycatFactStmt != nil {
		if cerr := q.saveHappycatFactStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveHappycatFactStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	getHappycatFactStmt   *sql.Stmt
	listHappycatFactsStmt *sql.Stmt
	saveHappycatFactStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		getHappycatFactStmt:   q.getHappycatFactStmt,
		listHappycatFactsStmt: q.listHappycatFactsStmt,
		saveHappycatFactStmt:  q.saveHappycatFactStmt,
	}
}
