// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type HappycatFact struct {
	ID        uuid.UUID `json:"id"`
	Fact      string    `json:"fact"`
	CreatedAt time.Time `json:"created_at"`
}
