---
apiVersion: jetstream.nats.io/v1beta2
kind: Consumer
metadata:
  name: wordstream-hasher
  namespace: PROJECT_NAME
spec:
  streamName: WORDS
  durableName: wordstream-hasher
  deliverPolicy: all
  filterSubject: WORDS.submitted
  maxDeliver: 20
  ackWait: "1000"
  ackPolicy: explicit
