application:
  port: 3000
  prettylog: false
  url:
    host: "localhost:3000"
    schemes: ["https"]
database:
    host: "127.0.0.1"
    port: 26257
    username: "archiver_app"
    password: "yourpass"
    databasename: "archiver"
    sslmode: "require"
observability:
  collector:
    host: "127.0.0.1"
    port: 4317