application:
  port: 3000
  prettylog: false  
database:
    host: "127.0.0.1"
    port: 26257
    username: "archiver_write"
    password: "yourpass"
    databasename: "archiver"
    sslmode: "require"
observability:
  collector:
    host: "127.0.0.1"
    port: 4317