apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: APP_NAME

commonLabels:
  app: APP_NAME

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - ingress.yaml
  - migrations.yaml
