application:
  port: 3000
  logpresetdev: false
catfact:
  url: "https://cat-fact.herokuapp.com/facts"
  timeout: "2s"
sentimenter:
  base_url: "http://sentimenter:3000/v1"
  timeout: "250ms"  
archiver:
  base_url: "http://archiver:3000/v1"
  timeout: "250ms"   
observability:
  collector:
    host: "127.0.0.1"
    port: 4317