definitions:
  http.ErrorResponse:
    properties:
      error_code:
        type: string
      error_msg:
        type: string
    type: object
  user.User:
    properties:
      created_at:
        type: string
      id:
        type: string
    type: object
info:
  contact:
    email: v@po.com
    name: Vince
    url: https://vincent.serpoul.com
  description: This is a sample server db save service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger gohttp API
paths:
  /user:
    post:
      description: createHandler creates a user
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.User'
      responses:
        "201":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: creates a user
      tags:
      - User
  /user/{userID}:
    get:
      description: getHandler returns a single cat fact by id
      parameters:
      - description: user id
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.ErrorResponse'
      summary: Get user by id
      tags:
      - user
swagger: "2.0"
